version: '3'
services:
  web:
    image: video-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`video.apollocompany.com.br`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=leresolver"
    environment:
      - NODE_ENV=production
    networks:
      - videoviewer
networks:
  videoviewer:
    external: true
